# Generated by Django 4.1.1 on 2022-09-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_alter_company_inception_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inception_date',
            field=models.DateField(null=True),
        ),
    ]
