# Generated by Django 4.1.1 on 2022-09-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_team_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='company',
            new_name='companyID',
        ),
    ]
