# Generated by Django 4.1.1 on 2022-09-21 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_rename_company_team_companyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inception_date',
            field=models.DateField(default=datetime.date(2022, 9, 21)),
        ),
    ]
